version: "3.8"

services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sredsol-website
    expose:
      - "4321"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: astro-nginx
    ports:
      - "80"
    depends_on:
      - astro
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
