name: Build and Publish Docker Image

on:
  push:
    branches:
      - main # Change to your deployment branch if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg CONTENT_API_KEY=${{ vars.CONTENT_API_KEY }} \
            --build-arg GHOST_URL=${{ vars.GHOST_URL }} \
            --build-arg SITE=${{ vars.SITE }} \
            --build-arg BASE_URL=${{ vars.BASE_URL }} \
            -t ghcr.io/${{ github.repository }}/astro-ssr:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/astro-ssr:latest
